services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lucienne
    restart: always
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app_container
    volumes:
      - ./:/app 
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres 
    restart: always
    command:  ["/app/cmd/start.sh"]