services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lucienne
    restart: always
    ports:
      - "5432:5432"
  app:
    image: gomex/luciene:latest
    platform: linux/amd64
    container_name: go_app_container
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    restart: always
    command:  ["/app/cmd/start.sh"]
