volumes:
  node_modules:
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
      - ./:/app
      - node_modules:/app/node_modules
      ports:
      - "${APP_PORT}:${APP_PORT}"
