---
- name: Deploy Docker Container
  hosts: all
  become: yes
  tasks:
    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create a directory for the application
      ansible.builtin.file:
        path: /opt/app
        state: directory
        mode: '0755'

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: ../../{{ item }}
        dest: /opt/app/{{ item }}
        mode: '0644'
      loop:
        - docker-compose.yml
        - local-compose-override.yml
        - .env

    - name: Deploy Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /opt/app
        state: present
        pull: "always"
        files:
          - /opt/app/docker-compose.yml
